# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 310)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(380, 280))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.calc_page = QtWidgets.QWidget()
        self.calc_page.setObjectName("calc_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.calc_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_calc_in = QtWidgets.QLineEdit(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_calc_in.setFont(font)
        self.le_calc_in.setInputMask("")
        self.le_calc_in.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_calc_in.setClearButtonEnabled(False)
        self.le_calc_in.setObjectName("le_calc_in")
        self.verticalLayout_2.addWidget(self.le_calc_in)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_mult = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_mult.setFont(font)
        self.btn_mult.setObjectName("btn_mult")
        self.gridLayout.addWidget(self.btn_mult, 0, 2, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 1, 3, 1, 1)
        self.btn_three = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_three.setFont(font)
        self.btn_three.setObjectName("btn_three")
        self.gridLayout.addWidget(self.btn_three, 3, 2, 1, 1)
        self.btn_brackets = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_brackets.setFont(font)
        self.btn_brackets.setObjectName("btn_brackets")
        self.gridLayout.addWidget(self.btn_brackets, 4, 0, 1, 1)
        self.btn_equals = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_equals.setFont(font)
        self.btn_equals.setObjectName("btn_equals")
        self.gridLayout.addWidget(self.btn_equals, 4, 3, 1, 1)
        self.btn_five = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_five.setFont(font)
        self.btn_five.setObjectName("btn_five")
        self.gridLayout.addWidget(self.btn_five, 2, 1, 1, 1)
        self.btn_eigth = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_eigth.setFont(font)
        self.btn_eigth.setObjectName("btn_eigth")
        self.gridLayout.addWidget(self.btn_eigth, 1, 1, 1, 1)
        self.btn_ac = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ac.setFont(font)
        self.btn_ac.setObjectName("btn_ac")
        self.gridLayout.addWidget(self.btn_ac, 0, 0, 1, 1)
        self.btn_seven = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_seven.setFont(font)
        self.btn_seven.setObjectName("btn_seven")
        self.gridLayout.addWidget(self.btn_seven, 1, 0, 1, 1)
        self.btn_div = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.gridLayout.addWidget(self.btn_div, 0, 1, 1, 1)
        self.btn_sub = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_sub.setFont(font)
        self.btn_sub.setObjectName("btn_sub")
        self.gridLayout.addWidget(self.btn_sub, 0, 3, 1, 1)
        self.btn_two = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_two.setFont(font)
        self.btn_two.setObjectName("btn_two")
        self.gridLayout.addWidget(self.btn_two, 3, 1, 1, 1)
        self.btn_one = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_one.setFont(font)
        self.btn_one.setObjectName("btn_one")
        self.gridLayout.addWidget(self.btn_one, 3, 0, 1, 1)
        self.btn_nine = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_nine.setFont(font)
        self.btn_nine.setObjectName("btn_nine")
        self.gridLayout.addWidget(self.btn_nine, 1, 2, 1, 1)
        self.btn_sqrt = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_sqrt.setFont(font)
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.gridLayout.addWidget(self.btn_sqrt, 3, 3, 1, 1)
        self.btn_four = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_four.setFont(font)
        self.btn_four.setObjectName("btn_four")
        self.gridLayout.addWidget(self.btn_four, 2, 0, 1, 1)
        self.btn_zero = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_zero.setFont(font)
        self.btn_zero.setObjectName("btn_zero")
        self.gridLayout.addWidget(self.btn_zero, 4, 1, 1, 1)
        self.btn_comma = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_comma.setFont(font)
        self.btn_comma.setObjectName("btn_comma")
        self.gridLayout.addWidget(self.btn_comma, 4, 2, 1, 1)
        self.btn_pow = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_pow.setFont(font)
        self.btn_pow.setObjectName("btn_pow")
        self.gridLayout.addWidget(self.btn_pow, 2, 3, 1, 1)
        self.btn_six = QtWidgets.QPushButton(self.calc_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_six.setFont(font)
        self.btn_six.setObjectName("btn_six")
        self.gridLayout.addWidget(self.btn_six, 2, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.calc_page)
        self.conv_page = QtWidgets.QWidget()
        self.conv_page.setObjectName("conv_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.conv_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.conv_page)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.currency_tab = QtWidgets.QWidget()
        self.currency_tab.setObjectName("currency_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.currency_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_curr_a = QtWidgets.QLabel(self.currency_tab)
        self.lbl_curr_a.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_curr_a.setObjectName("lbl_curr_a")
        self.gridLayout_2.addWidget(self.lbl_curr_a, 0, 0, 1, 1)
        self.cmb_curr_a = QtWidgets.QComboBox(self.currency_tab)
        self.cmb_curr_a.setObjectName("cmb_curr_a")
        self.gridLayout_2.addWidget(self.cmb_curr_a, 0, 1, 1, 1)
        self.le_curr_a = QtWidgets.QLineEdit(self.currency_tab)
        self.le_curr_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_curr_a.setObjectName("le_curr_a")
        self.gridLayout_2.addWidget(self.le_curr_a, 0, 2, 1, 1)
        self.lbl_curr_b = QtWidgets.QLabel(self.currency_tab)
        self.lbl_curr_b.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_curr_b.setObjectName("lbl_curr_b")
        self.gridLayout_2.addWidget(self.lbl_curr_b, 1, 0, 1, 1)
        self.cmb_curr_b = QtWidgets.QComboBox(self.currency_tab)
        self.cmb_curr_b.setObjectName("cmb_curr_b")
        self.gridLayout_2.addWidget(self.cmb_curr_b, 1, 1, 1, 1)
        self.le_curr_b = QtWidgets.QLineEdit(self.currency_tab)
        self.le_curr_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_curr_b.setObjectName("le_curr_b")
        self.gridLayout_2.addWidget(self.le_curr_b, 1, 2, 1, 1)
        self.lbl_exchange = QtWidgets.QLabel(self.currency_tab)
        self.lbl_exchange.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_exchange.setObjectName("lbl_exchange")
        self.gridLayout_2.addWidget(self.lbl_exchange, 2, 0, 1, 1)
        self.le_exchange = QtWidgets.QLineEdit(self.currency_tab)
        self.le_exchange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_exchange.setReadOnly(True)
        self.le_exchange.setObjectName("le_exchange")
        self.gridLayout_2.addWidget(self.le_exchange, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_refresh = QtWidgets.QPushButton(self.currency_tab)
        self.btn_refresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./img/sync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_refresh.setIcon(icon1)
        self.btn_refresh.setIconSize(QtCore.QSize(24, 24))
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout.addWidget(self.btn_refresh)
        self.btn_convert = QtWidgets.QPushButton(self.currency_tab)
        self.btn_convert.setObjectName("btn_convert")
        self.horizontalLayout.addWidget(self.btn_convert)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.currency_tab, "")
        self.distance_tab = QtWidgets.QWidget()
        self.distance_tab.setObjectName("distance_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.distance_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_dist_a = QtWidgets.QLabel(self.distance_tab)
        self.lbl_dist_a.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dist_a.setObjectName("lbl_dist_a")
        self.gridLayout_3.addWidget(self.lbl_dist_a, 0, 0, 1, 1)
        self.cmb_dist_a = QtWidgets.QComboBox(self.distance_tab)
        self.cmb_dist_a.setObjectName("cmb_dist_a")
        self.gridLayout_3.addWidget(self.cmb_dist_a, 0, 1, 1, 1)
        self.le_dist_a = QtWidgets.QLineEdit(self.distance_tab)
        self.le_dist_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_dist_a.setObjectName("le_dist_a")
        self.gridLayout_3.addWidget(self.le_dist_a, 0, 2, 1, 1)
        self.lbl_dist_b = QtWidgets.QLabel(self.distance_tab)
        self.lbl_dist_b.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dist_b.setObjectName("lbl_dist_b")
        self.gridLayout_3.addWidget(self.lbl_dist_b, 1, 0, 1, 1)
        self.cmb_dist_b = QtWidgets.QComboBox(self.distance_tab)
        self.cmb_dist_b.setObjectName("cmb_dist_b")
        self.gridLayout_3.addWidget(self.cmb_dist_b, 1, 1, 1, 1)
        self.le_dist_b = QtWidgets.QLineEdit(self.distance_tab)
        self.le_dist_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_dist_b.setObjectName("le_dist_b")
        self.gridLayout_3.addWidget(self.le_dist_b, 1, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.distance_tab, "")
        self.speed_tab = QtWidgets.QWidget()
        self.speed_tab.setObjectName("speed_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.speed_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_speed_a = QtWidgets.QLabel(self.speed_tab)
        self.lbl_speed_a.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_speed_a.setObjectName("lbl_speed_a")
        self.gridLayout_4.addWidget(self.lbl_speed_a, 0, 0, 1, 1)
        self.cmb_speed_a = QtWidgets.QComboBox(self.speed_tab)
        self.cmb_speed_a.setObjectName("cmb_speed_a")
        self.gridLayout_4.addWidget(self.cmb_speed_a, 0, 1, 1, 1)
        self.le_speed_a = QtWidgets.QLineEdit(self.speed_tab)
        self.le_speed_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_speed_a.setObjectName("le_speed_a")
        self.gridLayout_4.addWidget(self.le_speed_a, 0, 2, 1, 1)
        self.lbl_speed_b = QtWidgets.QLabel(self.speed_tab)
        self.lbl_speed_b.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_speed_b.setObjectName("lbl_speed_b")
        self.gridLayout_4.addWidget(self.lbl_speed_b, 1, 0, 1, 1)
        self.cmb_speed_b = QtWidgets.QComboBox(self.speed_tab)
        self.cmb_speed_b.setObjectName("cmb_speed_b")
        self.gridLayout_4.addWidget(self.cmb_speed_b, 1, 1, 1, 1)
        self.le_speed_b = QtWidgets.QLineEdit(self.speed_tab)
        self.le_speed_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_speed_b.setObjectName("le_speed_b")
        self.gridLayout_4.addWidget(self.le_speed_b, 1, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.speed_tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.conv_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 30))
        self.menubar.setObjectName("menubar")
        self.menuCalculator = QtWidgets.QMenu(self.menubar)
        self.menuCalculator.setObjectName("menuCalculator")
        self.menuView = QtWidgets.QMenu(self.menuCalculator)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCalculator = QtWidgets.QAction(MainWindow)
        self.actionCalculator.setObjectName("actionCalculator")
        self.actionConverter = QtWidgets.QAction(MainWindow)
        self.actionConverter.setObjectName("actionConverter")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuView.addAction(self.actionCalculator)
        self.menuView.addAction(self.actionConverter)
        self.menuCalculator.addAction(self.menuView.menuAction())
        self.menuCalculator.addSeparator()
        self.menuCalculator.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuCalculator.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_mult.setShortcut(_translate("MainWindow", "*"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_add.setShortcut(_translate("MainWindow", "+"))
        self.btn_three.setText(_translate("MainWindow", "3"))
        self.btn_three.setShortcut(_translate("MainWindow", "3"))
        self.btn_brackets.setText(_translate("MainWindow", "(...)"))
        self.btn_equals.setText(_translate("MainWindow", "="))
        self.btn_equals.setShortcut(_translate("MainWindow", "Enter"))
        self.btn_five.setText(_translate("MainWindow", "5"))
        self.btn_five.setShortcut(_translate("MainWindow", "5"))
        self.btn_eigth.setText(_translate("MainWindow", "8"))
        self.btn_eigth.setShortcut(_translate("MainWindow", "8"))
        self.btn_ac.setToolTip(_translate("MainWindow", "Clears the calculator"))
        self.btn_ac.setText(_translate("MainWindow", "AC"))
        self.btn_ac.setShortcut(_translate("MainWindow", "Del"))
        self.btn_seven.setText(_translate("MainWindow", "7"))
        self.btn_seven.setShortcut(_translate("MainWindow", "7"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_div.setShortcut(_translate("MainWindow", "/"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_sub.setShortcut(_translate("MainWindow", "-"))
        self.btn_two.setText(_translate("MainWindow", "2"))
        self.btn_two.setShortcut(_translate("MainWindow", "2"))
        self.btn_one.setText(_translate("MainWindow", "1"))
        self.btn_one.setShortcut(_translate("MainWindow", "1"))
        self.btn_nine.setText(_translate("MainWindow", "9"))
        self.btn_nine.setShortcut(_translate("MainWindow", "9"))
        self.btn_sqrt.setText(_translate("MainWindow", "sqrt(x)"))
        self.btn_sqrt.setShortcut(_translate("MainWindow", "Ctrl+/"))
        self.btn_four.setText(_translate("MainWindow", "4"))
        self.btn_four.setShortcut(_translate("MainWindow", "4"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_zero.setShortcut(_translate("MainWindow", "0"))
        self.btn_comma.setText(_translate("MainWindow", "."))
        self.btn_comma.setShortcut(_translate("MainWindow", "., ,"))
        self.btn_pow.setText(_translate("MainWindow", "**"))
        self.btn_pow.setShortcut(_translate("MainWindow", "Ctrl+*"))
        self.btn_six.setText(_translate("MainWindow", "6"))
        self.btn_six.setShortcut(_translate("MainWindow", "6"))
        self.lbl_curr_a.setText(_translate("MainWindow", "Currency (A)"))
        self.le_curr_a.setText(_translate("MainWindow", "0.0"))
        self.lbl_curr_b.setText(_translate("MainWindow", "Currency (B)"))
        self.le_curr_b.setText(_translate("MainWindow", "0.0"))
        self.lbl_exchange.setText(_translate("MainWindow", "Exchange rate"))
        self.le_exchange.setText(_translate("MainWindow", "0.0"))
        self.btn_refresh.setToolTip(_translate("MainWindow", "<html><head/><body><p>Attempts to refresh the currency exchange rates from a web service</p></body></html>"))
        self.btn_refresh.setShortcut(_translate("MainWindow", "F5"))
        self.btn_convert.setToolTip(_translate("MainWindow", "Convert Currency (A) Value to Currency (B)"))
        self.btn_convert.setText(_translate("MainWindow", "Convert"))
        self.btn_convert.setShortcut(_translate("MainWindow", "Enter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.currency_tab), _translate("MainWindow", "Currency"))
        self.lbl_dist_a.setText(_translate("MainWindow", "Distance (A)"))
        self.le_dist_a.setText(_translate("MainWindow", "0.0"))
        self.lbl_dist_b.setText(_translate("MainWindow", "Distance (B)"))
        self.le_dist_b.setText(_translate("MainWindow", "0.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.distance_tab), _translate("MainWindow", "Distance"))
        self.lbl_speed_a.setText(_translate("MainWindow", "Spped (A)"))
        self.le_speed_a.setText(_translate("MainWindow", "0.0"))
        self.lbl_speed_b.setText(_translate("MainWindow", "Speed (B)"))
        self.le_speed_b.setText(_translate("MainWindow", "0.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.speed_tab), _translate("MainWindow", "Speed"))
        self.menuCalculator.setTitle(_translate("MainWindow", "&Calculator"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuAbout.setTitle(_translate("MainWindow", "Abo&ut"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCalculator.setText(_translate("MainWindow", "&Calculator"))
        self.actionCalculator.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionConverter.setText(_translate("MainWindow", "C&onverter"))
        self.actionConverter.setShortcut(_translate("MainWindow", "Ctrl+Shift+V"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))

